language: java
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  fast_finish: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/endpoint/c6cc872b193cbad86273/529f9078ed5ab0b3bf04ef9a/
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn cobertura:cobertura
after_script:
  - ls -la
  - cd src/main/java
  - ls -la
  - cat ../../../target/site/cobertura/coverage.xml
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ../../../cc-test-reporter format-coverage -d -t cobertura ../../../target/site/cobertura/coverage.xml; fi
  - cat coverage/codeclimate.json
